name: Lint

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Run eslint
        run: bunx eslint
